name: velo_care
description: "A Flutter application for vehicle maintenance and care."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  path: ^1.8.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.6
  firebase_app_check: ^0.3.2+5

  # UI & Forms
  flutter_typeahead: ^5.2.0
  table_calendar: ^3.0.9
  provider: ^6.0.5
  shimmer: ^3.0.0  
  fl_chart: ^0.71.0

  # Media & Networking
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.11
  http: ^1.1.0
  flutter_svg: ^2.0.7

  # OBD-II & Bluetooth
  flutter_reactive_ble: ^5.0.3  
  permission_handler: ^12.0.0+1 
  percent_indicator: ^4.2.3  
  syncfusion_flutter_gauges: ^29.1.39 

  # Utility
  uuid: ^4.5.1 
  equatable: ^2.0.5
  
  # Mechanic Finder
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  logger: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/car.jpg
    - assets/logo.png
    - assets/document.png
    - assets/maintenan.png
    - assets/mechanic.png
    - assets/reminders.png
    - assets/services.png
    - assets/tips.png
    - assets/contact_us.png
    - assets/help_support.png
    - assets/loginbac.jpg
    - assets/obd.png
    - assets/insurance_icon.png
    
    - assets/brake.png
    - assets/battery.png
    - assets/engine.png
    - assets/temp.png
    - assets/fog-light.png
    - assets/high-beam.png
    - assets/oil.png
    - assets/tire-pressure.png
    - assets/traction-control.png
    - assets/abs.png
    - assets/maintenance.png
    - assets/cruise.png